-- ============================================================
-- Tabla   : OMNI_EMPRESA_PROGRAMA
-- Módulo  : GLOBAL (habilitación de programas por empresa)
-- Autor   : [JCFB]
-- Fecha   : 2026-09-20
-- Desc    : Habilitación/licenciamiento de programas por empresa
-- ============================================================

CREATE TABLE OMNIOPS.OMNI_EMPRESA_PROGRAMA (
    ID_EMPRESA_PROGRAMA       NUMBER(10)      GENERATED ALWAYS AS IDENTITY,
    CODIGO_EMPRESA_PROGRAMA   NUMBER(10)      NOT NULL,
    ID_EMPRESA                NUMBER(10)      NOT NULL,
    ID_PROGRAMA               NUMBER(5)       NOT NULL,
    ESTADO_EMPRESA_PROGRAMA   VARCHAR2(15)    DEFAULT 'ACTIVO' NOT NULL,
    FECHA_ACTIVACION          DATE            DEFAULT SYSDATE NOT NULL,
    FECHA_VENCIMIENTO         DATE,
    OBSERVACION_EMPRESA_PROG  VARCHAR2(300),
    FECHA_ALTA_EMPRESA_PROG   DATE            DEFAULT SYSDATE NOT NULL,
    USR_CREA_EMPRESA_PROG     VARCHAR2(50),
    FECHA_MOD_EMPRESA_PROG    DATE,
    USR_MOD_EMPRESA_PROG      VARCHAR2(50),
    --
    CONSTRAINT PK_OMNI_EMPRESA_PROGRAMA
        PRIMARY KEY (ID_EMPRESA_PROGRAMA),
    CONSTRAINT UQ_OMNI_EMP_PROG_CODIGO
        UNIQUE (CODIGO_EMPRESA_PROGRAMA),
    CONSTRAINT FK_OMNI_EMP_PROG_EMPRESA
        FOREIGN KEY (ID_EMPRESA) REFERENCES OMNIOPS.OMNI_EMPRESAS (ID_EMPRESA),
    CONSTRAINT FK_OMNI_EMP_PROG_PROGRAMA
        FOREIGN KEY (ID_PROGRAMA) REFERENCES OMNIOPS.OMNI_PROGRAMAS (ID_PROGRAMA),
    CONSTRAINT UQ_OMNI_EMP_PROG_EMP_PROG
        UNIQUE (ID_EMPRESA, ID_PROGRAMA),
    CONSTRAINT CK_OMNI_EMP_PROG_ESTADO
        CHECK (ESTADO_EMPRESA_PROGRAMA IN ('ACTIVO','SUSPENDIDO','INACTIVO'))
);

COMMENT ON TABLE OMNIOPS.OMNI_EMPRESA_PROGRAMA IS
    'Habilitación de programas/módulos por empresa. Una empresa solo puede acceder a los programas que tenga ACTIVO en esta tabla. Actúa como capa de licenciamiento y seguridad.';

COMMENT ON COLUMN OMNIOPS.OMNI_EMPRESA_PROGRAMA.ID_EMPRESA_PROGRAMA     IS 'Identificador único del registro (PK)';
COMMENT ON COLUMN OMNIOPS.OMNI_EMPRESA_PROGRAMA.CODIGO_EMPRESA_PROGRAMA IS 'Código numérico del registro (usado en lógica del sistema)';
COMMENT ON COLUMN OMNIOPS.OMNI_EMPRESA_PROGRAMA.ID_EMPRESA              IS 'Empresa habilitada (FK a OMNI_EMPRESAS)';
COMMENT ON COLUMN OMNIOPS.OMNI_EMPRESA_PROGRAMA.ID_PROGRAMA             IS 'Programa/módulo habilitado (FK a OMNI_PROGRAMAS)';
COMMENT ON COLUMN OMNIOPS.OMNI_EMPRESA_PROGRAMA.ESTADO_EMPRESA_PROGRAMA IS 'Estado de la habilitación: ACTIVO / SUSPENDIDO / INACTIVO';
COMMENT ON COLUMN OMNIOPS.OMNI_EMPRESA_PROGRAMA.FECHA_ACTIVACION        IS 'Fecha desde la cual el programa está habilitado para la empresa';
COMMENT ON COLUMN OMNIOPS.OMNI_EMPRESA_PROGRAMA.FECHA_VENCIMIENTO       IS 'Fecha de vencimiento del licenciamiento (NULL = sin vencimiento)';
COMMENT ON COLUMN OMNIOPS.OMNI_EMPRESA_PROGRAMA.OBSERVACION_EMPRESA_PROG IS 'Observaciones sobre la habilitación';
COMMENT ON COLUMN OMNIOPS.OMNI_EMPRESA_PROGRAMA.FECHA_ALTA_EMPRESA_PROG IS 'Fecha de alta del registro (auditoría)';
COMMENT ON COLUMN OMNIOPS.OMNI_EMPRESA_PROGRAMA.USR_CREA_EMPRESA_PROG   IS 'Usuario que creó el registro (auditoría)';
COMMENT ON COLUMN OMNIOPS.OMNI_EMPRESA_PROGRAMA.FECHA_MOD_EMPRESA_PROG  IS 'Fecha de última modificación (auditoría)';
COMMENT ON COLUMN OMNIOPS.OMNI_EMPRESA_PROGRAMA.USR_MOD_EMPRESA_PROG    IS 'Usuario que modificó el registro (auditoría)';