-- ============================================================
-- Tabla   : OMNI_USUARIO_EMPRESA
-- Módulo  : GLOBAL (relación usuario ↔ empresa)
-- Autor   : [JCFB]
-- Fecha   : 2026-09-21
-- Desc    : Asignación de usuarios a empresas (N:M)
-- ============================================================

CREATE TABLE OMNIOPS.OMNI_USUARIO_EMPRESA (
    ID_USUARIO_EMPRESA       NUMBER(10)      GENERATED ALWAYS AS IDENTITY,
    CODIGO_USUARIO_EMPRESA   NUMBER(10)      NOT NULL,
    ID_USUARIO               NUMBER(10)      NOT NULL,
    ID_EMPRESA               NUMBER(10)      NOT NULL,
    ES_EMPRESA_PRINCIPAL     VARCHAR2(1)     DEFAULT 'N' NOT NULL,
    ESTADO_USUARIO_EMPRESA   VARCHAR2(15)    DEFAULT 'ACTIVO' NOT NULL,
    FECHA_ASIGNACION         DATE            DEFAULT SYSDATE NOT NULL,
    OBSERVACION_USUARIO_EMP  VARCHAR2(300),
    FECHA_ALTA_USUARIO_EMP   DATE            DEFAULT SYSDATE NOT NULL,
    USR_CREA_USUARIO_EMP     VARCHAR2(50),
    FECHA_MOD_USUARIO_EMP    DATE,
    USR_MOD_USUARIO_EMP      VARCHAR2(50),
    --
    CONSTRAINT PK_OMNI_USUARIO_EMPRESA
        PRIMARY KEY (ID_USUARIO_EMPRESA),
    CONSTRAINT UQ_OMNI_USR_EMP_CODIGO
        UNIQUE (CODIGO_USUARIO_EMPRESA),
    CONSTRAINT FK_OMNI_USR_EMP_USUARIO
        FOREIGN KEY (ID_USUARIO) REFERENCES OMNIOPS.OMNI_USUARIOS (ID_USUARIO),
    CONSTRAINT FK_OMNI_USR_EMP_EMPRESA
        FOREIGN KEY (ID_EMPRESA) REFERENCES OMNIOPS.OMNI_EMPRESAS (ID_EMPRESA),
    CONSTRAINT UQ_OMNI_USR_EMP_USR_EMP
        UNIQUE (ID_USUARIO, ID_EMPRESA),
    CONSTRAINT CK_OMNI_USR_EMP_PRINCIPAL
        CHECK (ES_EMPRESA_PRINCIPAL IN ('S','N')),
    CONSTRAINT CK_OMNI_USR_EMP_ESTADO
        CHECK (ESTADO_USUARIO_EMPRESA IN ('ACTIVO','SUSPENDIDO','INACTIVO'))
);

COMMENT ON TABLE OMNIOPS.OMNI_USUARIO_EMPRESA IS
    'Relación N:M entre usuarios y empresas. Un usuario global puede pertenecer a varias empresas; se marca cuál es su empresa principal por defecto.';

COMMENT ON COLUMN OMNIOPS.OMNI_USUARIO_EMPRESA.ID_USUARIO_EMPRESA     IS 'Identificador único del registro (PK)';
COMMENT ON COLUMN OMNIOPS.OMNI_USUARIO_EMPRESA.CODIGO_USUARIO_EMPRESA IS 'Código numérico del registro (usado en lógica del sistema)';
COMMENT ON COLUMN OMNIOPS.OMNI_USUARIO_EMPRESA.ID_USUARIO             IS 'Usuario asignado (FK a OMNI_USUARIOS)';
COMMENT ON COLUMN OMNIOPS.OMNI_USUARIO_EMPRESA.ID_EMPRESA             IS 'Empresa a la que pertenece el usuario (FK a OMNI_EMPRESAS)';
COMMENT ON COLUMN OMNIOPS.OMNI_USUARIO_EMPRESA.ES_EMPRESA_PRINCIPAL   IS 'Indica si es la empresa principal del usuario (S/N) — se usa al loguear';
COMMENT ON COLUMN OMNIOPS.OMNI_USUARIO_EMPRESA.ESTADO_USUARIO_EMPRESA IS 'Estado de la asignación: ACTIVO / SUSPENDIDO / INACTIVO';
COMMENT ON COLUMN OMNIOPS.OMNI_USUARIO_EMPRESA.FECHA_ASIGNACION        IS 'Fecha en que se asignó el usuario a la empresa';
COMMENT ON COLUMN OMNIOPS.OMNI_USUARIO_EMPRESA.OBSERVACION_USUARIO_EMP IS 'Observaciones sobre la asignación';
COMMENT ON COLUMN OMNIOPS.OMNI_USUARIO_EMPRESA.FECHA_ALTA_USUARIO_EMP  IS 'Fecha de alta del registro (auditoría)';
COMMENT ON COLUMN OMNIOPS.OMNI_USUARIO_EMPRESA.USR_CREA_USUARIO_EMP    IS 'Usuario que creó el registro (auditoría)';
COMMENT ON COLUMN OMNIOPS.OMNI_USUARIO_EMPRESA.FECHA_MOD_USUARIO_EMP   IS 'Fecha de última modificación (auditoría)';
COMMENT ON COLUMN OMNIOPS.OMNI_USUARIO_EMPRESA.USR_MOD_USUARIO_EMP     IS 'Usuario que modificó el registro (auditoría)';