-- ============================================================
-- Tabla   : OMNI_PERSONAS
-- Módulo  : GLOBAL (transversal a todos los módulos)
-- Autor   : Juan Carlos
-- Fecha   : 2026-09-23
-- Desc    : Personas físicas y jurídicas del sistema
-- ============================================================

CREATE TABLE OMNIOPS.OMNI_PERSONAS (
    ID_PERSONA                  NUMBER(10)      GENERATED ALWAYS AS IDENTITY,
    CODIGO_PERSONA              NUMBER(10)      NOT NULL,
    TIPO_PERSONA                VARCHAR2(10)    NOT NULL,
    TIPO_DOCUMENTO_PERSONA      VARCHAR2(10)    NOT NULL,
    NRO_DOCUMENTO_PERSONA       VARCHAR2(20)    NOT NULL,
    NOMBRE_PERSONA              VARCHAR2(150)   NOT NULL,
    NOMBRE_FANTASIA_PERSONA     VARCHAR2(150),
    FECHA_NACIMIENTO_PERSONA    DATE,
    EMAIL_PERSONA               VARCHAR2(100),
    TELEFONO_PERSONA            VARCHAR2(30),
    CELULAR_PERSONA             VARCHAR2(30),
    DIRECCION_PERSONA           VARCHAR2(200),
    CIUDAD_PERSONA              VARCHAR2(100),
    DEPARTAMENTO_PERSONA        VARCHAR2(100),
    ESTADO_PERSONA              VARCHAR2(10)    DEFAULT 'ACTIVO' NOT NULL,
    OBSERVACION_PERSONA         VARCHAR2(300),
    FECHA_ALTA_PERSONA          DATE            DEFAULT SYSDATE NOT NULL,
    USR_CREA_PERSONA            VARCHAR2(50),
    FECHA_MOD_PERSONA           DATE,
    USR_MOD_PERSONA             VARCHAR2(50),
    --
    CONSTRAINT PK_OMNI_PERSONAS
        PRIMARY KEY (ID_PERSONA),
    CONSTRAINT UQ_OMNI_PERSONAS_CODIGO
        UNIQUE (CODIGO_PERSONA),
    CONSTRAINT UQ_OMNI_PERSONAS_DOC
        UNIQUE (TIPO_DOCUMENTO_PERSONA, NRO_DOCUMENTO_PERSONA),
    CONSTRAINT CK_OMNI_PERSONAS_TIPO
        CHECK (TIPO_PERSONA IN ('FISICA','JURIDICA')),
    CONSTRAINT CK_OMNI_PERSONAS_TIPO_DOC
        CHECK (TIPO_DOCUMENTO_PERSONA IN ('DNI','RUC','PASAPORTE','CI')),
    CONSTRAINT CK_OMNI_PERSONAS_ESTADO
        CHECK (ESTADO_PERSONA IN ('ACTIVO','INACTIVO','BLOQUEADO'))
);

COMMENT ON TABLE OMNIOPS.OMNI_PERSONAS IS
    'Personas físicas y jurídicas del sistema OmniOpsys. Base común para clientes, usuarios, empleados, proveedores, etc.';

COMMENT ON COLUMN OMNIOPS.OMNI_PERSONAS.ID_PERSONA               IS 'Identificador único de la persona (PK)';
COMMENT ON COLUMN OMNIOPS.OMNI_PERSONAS.CODIGO_PERSONA           IS 'Código numérico de la persona (lógica)';
COMMENT ON COLUMN OMNIOPS.OMNI_PERSONAS.TIPO_PERSONA             IS 'Tipo: FISICA / JURIDICA';
COMMENT ON COLUMN OMNIOPS.OMNI_PERSONAS.TIPO_DOCUMENTO_PERSONA   IS 'Tipo de documento: DNI / RUC / PASAPORTE / CI';
COMMENT ON COLUMN OMNIOPS.OMNI_PERSONAS.NRO_DOCUMENTO_PERSONA    IS 'Número de documento (puede incluir dígito verificador)';
COMMENT ON COLUMN OMNIOPS.OMNI_PERSONAS.NOMBRE_PERSONA           IS 'Nombre completo o razón social';
COMMENT ON COLUMN OMNIOPS.OMNI_PERSONAS.NOMBRE_FANTASIA_PERSONA  IS 'Nombre de fantasía (para personas jurídicas)';
COMMENT ON COLUMN OMNIOPS.OMNI_PERSONAS.FECHA_NACIMIENTO_PERSONA IS 'Fecha de nacimiento o constitución';
COMMENT ON COLUMN OMNIOPS.OMNI_PERSONAS.EMAIL_PERSONA            IS 'Email de contacto';
COMMENT ON COLUMN OMNIOPS.OMNI_PERSONAS.TELEFONO_PERSONA         IS 'Teléfono fijo';
COMMENT ON COLUMN OMNIOPS.OMNI_PERSONAS.CELULAR_PERSONA          IS 'Teléfono celular';
COMMENT ON COLUMN OMNIOPS.OMNI_PERSONAS.DIRECCION_PERSONA        IS 'Dirección principal';
COMMENT ON COLUMN OMNIOPS.OMNI_PERSONAS.CIUDAD_PERSONA           IS 'Ciudad';
COMMENT ON COLUMN OMNIOPS.OMNI_PERSONAS.DEPARTAMENTO_PERSONA     IS 'Departamento / provincia / estado';
COMMENT ON COLUMN OMNIOPS.OMNI_PERSONAS.ESTADO_PERSONA           IS 'Estado: ACTIVO / INACTIVO / BLOQUEADO';
COMMENT ON COLUMN OMNIOPS.OMNI_PERSONAS.OBSERVACION_PERSONA      IS 'Observaciones generales';
COMMENT ON COLUMN OMNIOPS.OMNI_PERSONAS.FECHA_ALTA_PERSONA       IS 'Fecha de alta (auditoría)';
COMMENT ON COLUMN OMNIOPS.OMNI_PERSONAS.USR_CREA_PERSONA         IS 'Usuario que creó (auditoría)';
COMMENT ON COLUMN OMNIOPS.OMNI_PERSONAS.FECHA_MOD_PERSONA        IS 'Fecha de última modificación (auditoría)';
COMMENT ON COLUMN OMNIOPS.OMNI_PERSONAS.USR_MOD_PERSONA          IS 'Usuario que modificó (auditoría)';